yctmarket/ent/urls.py
from django.urls import path, re_path

from . import views

app_name = 'ent'

#urlpatterns = [
    #path('', views.article_list, name='home'),
    #url(r'^comment/$', views.comment, name='comment'),
    #path(?P<id>\d+)/post_edit/$', views.post_edit, name="post_edit"),
    #path(?P<id>\d+)/post_delete/$', views.post_delete, name="post_delete"),
    #path(?P<id>\d+)/favourite_post/$', views.favourite_post, name="favourite_post"),
    #path((?P<id>\d+)/(?P<slug>[\w-]+)/$', views.article_details, name="article_details"),
    #path('post_create/$', views.post_create, name="post_create"),
    #path('edit_profile/$', views.edit_profile, name="edit_profile"),
#]
urlpatterns = [
    path('', views.article_list, name='article_list'),

    re_path(r'(?P<id>\d+)/(?P<slug>[\w-]+)/(?P<amount>\d+)/$', views.advert_details, name="advert_detail"),
    re_path(r'(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.article_details, name="article_detail"), #using function views here

    #re_path('activate/<uidb64>/<token>', yct_views.ActivateAccountView.as_view(), name="activate"),
    #re_path(r'(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.ArticleDetail.as_view(), name="article_detail"), #using class based views here


]

yctmarket/yctmarket/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from ent import views as yct_views
from contact import views as contact_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('ent.urls', namespace="ent")),
    #path('', include('users.urls', namespace="users")),
    path('contact/', contact_views.contact_page, name="contact_page"),
    #path('fetch_post/', yct_views.fetch_post, name='fetch_post'),
    path('about/', yct_views.about, name="about"),
    path('thank_you/', yct_views.thank_you, name="thank_you"),
    path('thanks/', yct_views.thanks, name="thanks"),
    path('paystack_confirmation/', yct_views.paystack_confirmation, name="paystack_confirmation"),
    path('login/', yct_views.user_login, name="user_login"),
    #path('post_create/', yct_views.post_create, name="post_create"),
    path('plan/', yct_views.plan, name="plan"),
    #path('posts/', yct_views.PostList.as_view(), name="posts"),
    #path('cart/', include('cart.urls', namespace='cart')),
    path('pay_per_upload/', yct_views.pay_per_upload, name="pay_per_upload"),
    path('upload_free_at_given/', yct_views.upload_free_at_given, name="upload_free_at_given"),
    path('re_request_activation_link/', yct_views.re_request_activation, name="re_request_activation_link"),
    path('activate/<uidb64>/<token>', yct_views.activate, name="activate"),
    path('logout/', yct_views.user_logout, name="user_logout"),
    path('signup/', yct_views.signup_view, name="signup_view"),
    #path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    #path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yctmarket/ent/forms.py
from django import forms
from django.core.validators import RegexValidator

#class CommentArticle(forms.ModelForm):
	#class Meta:
		#model = models.Article
		#fields = ['title', 'body', 'slug', 'thumb']
from .models import Article, Post, InfiniteScroll
from django.contrib.auth.models import User


class RequiredFieldsMixin():

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        fields_required = getattr(self.Meta, 'fields_required', None)

        if fields_required:
            for key in self.fields:
                if key not in fields_required:
                    self.fields[key].required = False



class InfiniteScrollForm(forms.ModelForm):

    class Meta:
        model = InfiniteScroll
        fields = (
            'start',
            'end',
            )

class EmailFormForPayment(forms.ModelForm):
    firstname = forms.CharField(required=True, label='First Name',max_length=100)
    lastname = forms.CharField(required=True, label='Last Name', max_length=100)
    address = forms.CharField(required=True, widget=forms.Textarea)
    email = forms.EmailField(required=True)
    phoneNumber = forms.CharField(required=True, max_length=11)
    def clean_number1(self):
        n = self.cleaned_data.get('phoneNumber')
        print(n)
        allowed_characters = '0123456789'
        for char in n:
            if char not in allowed_characters:
                raise forms.ValidationError("Please only use digits")
        return n


    class Meta:
        model = Post
        exclude = ('title',
        'reference',
        'description',
        'bodysnippet',
        'slug',
        'author',
        'category',
        'updated',
        'body',
        'duration',
        'created',
        'image',
        'image2',
        'image3',
        'video',
        'view_count',
        'status',
        'amount',
        )



class EmailFormForMeetUp(forms.ModelForm):
    firstname = forms.CharField(required=True, label='First Name',max_length=100)
    lastname = forms.CharField(required=True, label='Last Name', max_length=100)
    address = forms.CharField(required=True, widget=forms.Textarea)
    email = forms.EmailField(required=True)
    phoneNumber = forms.CharField(required=True, max_length=11)
    def clean_number1(self):
        n = self.cleaned_data.get('phoneNumber')
        print(n)
        allowed_characters = '0123456789'
        for char in n:
            if char not in allowed_characters:
                raise forms.ValidationError("Please only use digits")
        return n
    class Meta:
        model = Post
        exclude = ('title',
        'reference',
        'description',
        'bodysnippet',
        'slug',
        'author',
        'category',
        'updated',
        'body',
        'duration',
        'created',
        'image',
        'image2',
        'image3',
        'video',
        'view_count',
        'status',
        'amount',
        )

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            'category',
            'title',
            'description',
            'duration',
            'available',
            'amount',
            'image',
            'image2',
            'image3',
            'status',
        )

class PostCreateFormForFree(forms.ModelForm):

    class Meta:
        model = Post
        fields = (
            'category',
            'title',
            'description',
            'amount',
            'image',
            'image2',
            'image3',
            'available',
            'status',
        )



class UserLoginForm(forms.Form):
    username = forms.CharField(label="", widget= forms.TextInput(attrs = {'placeholder':'Username'}))
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs = {'placeholder':'Password'}))


class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(widget = forms.PasswordInput())
    password2 = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            )


    def clean_confirm_password(self):
        password = self.cleaned_data.get('password1')
        confirm_password = self.cleaned_data.get('password2')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Password Mismatch")
        return email


class UserEditForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

#class ProfileEditForm(forms.ModelForm):
#    class Meta:
#        model = Profile
#        exclude = ('user',)
class ReRequestActivationForm(forms.Form):
    email = forms.EmailField(required=True)

yctmarket/ent/templates/ent/activate.html
{% autoescape off %}

Hi {{ user.username }}
Please click the link below to verify your account

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}

{% endautoescape %}

yctmarket/ent/templates/ent/activate_failed.html
{% extends 'ent/base.html' %}






{% load crispy_forms_tags %}  <!-- check meerasblog settings.py for this -->

{% block style %}
  <style>
  #fix {
    position: fixed;
    bottom: 0px;
    width: 100%;
  }

  .set1 {
    display: grid;
    grid-gap: 20px;
    grid-template-columns: auto;
    grid-template-areas:
      'contact';
}
  </style>


{% endblock %}


{% block container %}
<h3>
	Something went wrong, please re request the activation link <a href="{% url 're_request_activation_link' %}">here</a>
</h3>

{% endblock %}

yctmarket/ent/templates/ent/advert_detail.html
{% extends 'ent/base.html' %}



{% block title %}{{ post.title|title }} | {{ block.super }}{% endblock %}

{% block tweet %}
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@tonybrainsblog">
<meta name="twitter:creator" content="@tonybrainsblog">
<meta name="twitter:url" content="" href="{{ post.get_absolute_url }}">
<meta name="twitter:title" content="{{ post.title|linebreaks }}">
<meta name="twitter:description" content="{{ post.description|linebreaks }}">
 <meta name="twitter:image" content="{{ url }}">
<meta property="og:title" content="{{ post.title|linebreaks }}" />
<meta property="og:type" content="article" />
<meta property="og:description" content="{{ post.description|linebreaks }}" />
<meta property="og:url" content="" href="{{ post.get_absolute_url }}" />
<meta property="og:image" content="{{ url }}" />

<meta name="description" content="{{ post.snippet|safe }}">
<meta name="keywords" content="{{ post.snippet|safe }}">

{% endblock %}


{% block lin %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% endblock %}





{% block content %}

<section id="" class="">
  <div class="row">
<div class="col-md-8">
<div class="row">
  <div class="col-md-8">

    {% if post.pic %}

    
    <img class="main-image mySlides" src="{{ post.pic.url }}" style="width:100%"/>
    
  </div>
    {% endif %}
  </div> <!-- col-md-4 -->
  <br><br>
  <div class="col-md-8" style="background-color: white;">
    <h2 id="increase">{{ post.title|upper }}</h2>
    <hr/>
    <br>
    <div class="price">Sponsor: {{ post.company_name }}</div>
    <hr/>

    <h3 id="increase">Description<h3>

    <div style="margin-left: 20px;color: #df1057;" class="panel-body">
            {{ post.description|linebreaks }} </div>


    
      <hr/>
      
      
          </div>
        </div> <!-- col-md-8 -->
      </div> <!-- row -->
      </div> <!-- col-md-8 -->
      

        </div> <!-- row -->
      </section>


<div id="addQuestion">
  <div class="col-sm-8 form-group-lg">



  <br>

</div>
</div>
    <br/><br/><br/>

{% endblock %}



{% block java %}
  <script>

  function currentDiv(n) {
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
  }
  x[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " w3-opacity-off";
}



    </script>
    {% endblock %}

yctmarket/ent/templates/ent/navbar.html
{% load staticfiles %}



<nav>
    <div class="lines">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
    </div>

    <div class="logo">
        <a href="{% url 'ent:article_list' %}">
        <img src="{% static 'img/yctmarket.png' %}" alt="Image Not Found">
        </a>
    </div>


    <ul class="nav-links">
        {% url 'ent:article_list' as article_list %}
        {% url 'about' as about %}
        {% url 'upload_free_at_given' as upload_free_at_given %}
        {% url 'contact_page' as contact_page %}
        <li >
            <a class="{% if request.path == article_list %}active{% endif %}" href="{% url 'ent:article_list' %}">Market</a>
        </li>


        <li >
            <a class="{% if request.path == post_create %}active{% endif %}" href="{% url 'upload_free_at_given' %}">Post</a>
        </li>

        <li>
            <a class="{% if request.path == contact_page %}active{% endif %}" href="{% url 'contact_page' %}">Contact</a>
        </li>

        <li>
            <a class="{% if request.path == about %}active{% endif %}" href="{% url 'about' %}">Policy</a>
        </li>

        {% if not request.user.is_authenticated %}

            <li >
            <a class="{% if request.path == user_login  %}active{% endif %}" href="{% url 'user_login' %}" >login</a>
            </li>
                <li >
                <a class="{% if request.path == signup_view %}active{% endif %}" href="{% url 'signup_view' %}">Sign-Up</a>
            </li>
        {% else %}


          <li>
              <a  href="{% url 'user_logout' %}">Logout</a>
          </li>


        {% endif %}


    </ul>


</nav>

yctmarket/ent/templates/ent/password_reset_confirm.html
{% extends 'ent/base.html' %}


{% load crispy_forms_tags %}

{% block style %}
  <style>
  #fix {
    position: fixed;
    bottom: 0px;
    width: 100%;
  }

  .set1 {
    display: grid;
    grid-gap: 20px;
    grid-template-columns: auto;
    grid-template-areas:
      'contact';
}
  </style>


{% endblock %}

{% block content %}




<div id="addQuestion">
  <div class="col-sm-8 form-group-lg">

  {% if validlink %}
    <h2>Change password</h2>
    <br/>
    <form method="post">
      {% csrf_token %}

    <div>
      {% if form.new_password1 %}
      {{ form.new_password1 }}<br>
      {% endif %}
      </div>

    <div>
      {% if form.new_password2 %}
      {{ form.new_password2 }}<br>
      {% endif %}
      </div>

      <button class="btn btn-success">Change password</button>
    </form>
    </div>
</div>
    <br/><br/><br/>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}





{% block java %}
  <script>

var new_password1 = document.querySelector('#id_new_password1');
var new_password2 = document.querySelector('#id_new_password2');



new_password1.setAttribute('class', 'form-control');
new_password1.setAttribute('placeholder', 'New password');
new_password2.setAttribute('class', 'form-control');
new_password2.setAttribute('placeholder', 'New password confirmation');

new_password1.required = true;
new_password1.required = true;

var error = document.querySelector('li');
error.style.color = red;

    </script>
    {% endblock %}

yctmarket/ent/templates/ent/profile.html
{% extends 'ent/base.html' %}



{% block title %}{{ post.title|title }} | {{ block.super }}{% endblock %}

{% block tweet %}
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@tonybrainsblog">
<meta name="twitter:creator" content="@tonybrainsblog">
<meta name="twitter:url" content=href="{{ post.get_absolute_url }}">
<meta name="twitter:title" content="{{ post.title|linebreaks }}">
<meta name="twitter:description" content="{{ post.description|linebreaks }}">
<!--  <meta name="twitter:image" content="{{ url }}">  -->

<meta property="og:title" content="{{ post.title|linebreaks }}" />
<meta property="og:type" content="article" />
<meta property="og:description" content="{{ post.description|linebreaks }}" />
<meta property="og:url" content=href="{{ post.get_absolute_url }}" />
<!-- <meta property="og:image" content="{{ url }}" /> -->

<meta name="description" content="{{ post.snippet|safe }}">
<meta name="keywords" content="{{ post.snippet|safe }}">


{% endblock %}


{% block lin %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% endblock %}



{% block content %}

<section id="" class="">
  <div class="row">
<div class="col-md-8">
<div class="row">
  <div class="col-md-4 w3-content">

    {% if post.image %}

    <img class="main-image mySlides" src="{{ post.image2.url }}" style="width:100%;display:none"/>
    <img class="main-image mySlides" src="{{ post.image.url }}" style="width:100%"/>
    <img class="main-image mySlides" src="{{ post.image3.url }}" style="width:100%;display:none"/>
    <div class="w3-row-padding w3-section">
    <div class="w3-col s4">
      <img class="demo w3-opacity w3-hover-opacity-off" src="{{ post.image2.url }}" style="width:100%;cursor:pointer" onclick="currentDiv(1)">
    </div>
    <div class="w3-col s4">
      <img class="demo w3-opacity w3-hover-opacity-off" src="{{ post.image.url }}" style="width:100%;cursor:pointer" onclick="currentDiv(2)">
    </div>
    <div class="w3-col s4">
      <img class="demo w3-opacity w3-hover-opacity-off" src="{{ post.image3.url }}" style="width:100%;cursor:pointer" onclick="currentDiv(3)">
    </div>
  </div>
    {% endif %}
  </div> <!-- col-md-4 -->
  <br><br>
  <div class="col-md-8">
    <h2 id="increase">{{ post.title|upper }}</h2>
    <br>
    <div class="price">Price: {{ post.amount }} NGN</div>
    <hr/>


    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingOne">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Description
            </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
          <div class="panel-body">
            {{ post.description }} </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingTwo">
          <h4 class="panel-title">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Specifications
            </a>
          </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="panel-body">
            {{ post.specification }} </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingThree">
          <h4 class="panel-title">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Related
            </a>
          </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
          <div class="panel-body">
            {{ post.related }}  </div>
        </div>
      </div>
          </div>
        </div> <!-- col-md-8 -->
      </div> <!-- row -->
      </div> <!-- col-md-8 -->
      <div class="col-md-4">
      <div class="list-group">
        <a href="#" class="list-group-item">Category One</a>
        <a href="#" class="list-group-item">Category Two</a>
        <a href="#" class="list-group-item">Category Three</a>
        <a href="#" class="list-group-item">Category Four</a>
        <a href="#" class="list-group-item">Category Five</a>
      </div>
      </div> <!-- col-md-4 -->
        </div> <!-- row -->
      </section>











    <br/><br/><br/>

<div id="addQuestion">
  <div class="col-sm-8 form-group-lg">


<form class="form-group" method="post"  action="{% url 'ent:article_detail' id=post.id slug=post.slug %}" >
  {% csrf_token %}

  {% if form.firstname %}
  {{ form.firstname }}<br>
  {% endif %}

  {% if form.lastname %}
  {{ form.lastname }}<br>
  {% endif %}

  {% if form.email %}
  {{ form.email }}<br>
  {% endif %}

  {% if form.address %}
  {{ form.address }}<br>
  {% endif %}

  {% if form.phoneNumber %}
  {{ form.phoneNumber }}<br>
  {% endif %}
<select class="form-control">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
</select>

    <button class="btn btn-success">Buy Now</button>
  </form>
</div>
</div>
    <br/><br/><br/>

{% endblock %}



{% block java %}
  <script>

  function currentDiv(n) {
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  if (n > x.length) {slideIndex = 1}
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
  }
  x[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " w3-opacity-off";
}


var firstname = document.querySelector('#id_firstname');
var lastname = document.querySelector('#id_lastname');
var email = document.querySelector('#id_email');
var address = document.querySelector('#id_address');
var phoneNumber = document.querySelector('#id_phoneNumber');



firstname.setAttribute('class', 'form-control');
firstname.setAttribute('placeholder', 'First Name');
lastname.setAttribute('class', 'form-control');
lastname.setAttribute('placeholder', 'Last Name');
email.setAttribute('class', 'form-control');
email.setAttribute('placeholder', 'Email');
address.setAttribute('class', 'form-control');
address.setAttribute('placeholder', 'Address');
phoneNumber.setAttribute('class', 'form-control');
phoneNumber.setAttribute('placeholder', 'Phone Number');

firstname.required = true;
lastname.required = true;
email.required = true;
address.required = true;
phoneNumber = true;

var error = document.querySelector('li');
error.style.color = red;

    </script>
    {% endblock %}

yctmarket/ent/templates/ent/register.html
{% extends 'ent/base.html' %}
{% load crispy_forms_tags %}

{% block container %}


<div id="set1" style="display:unset">

     <div class="limiter">


{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div>
                <strong id='err'>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div>
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

            <div class="container-login100">
              <div class="wrap-login100 normal">


              {% if form %}
                <form method="post" action="{% url 'signup_view' %}" class="login100-form validate-form p-l-55 p-r-55 p-t-178">
                  {% csrf_token %}
                  <span class="login100-form-title">
                    Sign Up
                  </span>

                  <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.username }}

                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.username.errors }}</div>
                  {% endif %}


                  <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.first_name }}

                    <span class="focus-input100"></span>
                  </div>

                   <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.last_name }}

                    <span class="focus-input100"></span>
                  </div>

                   <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.email }}

                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.email.errors }}</div>
                  {% endif %}

                  <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.phoneNumber }}

                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.phoneNumber.errors }}</div>
                  {% endif %}

                   <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.password1 }}

                    <span class="focus-input100"></span>
                  </div>

                   <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.password2 }}


                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.errors.password2 }}</div>
                  {% endif %}



                  <div class="text-right p-t-13 p-b-23">
                    <span class="txt1">
                      Forgot
                    </span>

                    <a href="#" class="txt2">
                      Username / Password?
                    </a>
                  </div>

                  <div class="container-login100-form-btn">
                    <button id="submitt" class="login100-form-btn">
                      Sign up
                    </button>
                  </div>
                  <br>

                  {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <br>
                  {% endif %}

                  <div class="flex-col-c p-t-170 p-b-40">
                    <span class="txt1 p-b-9">
                      Already have an account?
                    </span>

                    <a href="{% url 'user_login' %}" class="txt3">
                      Login
                    </a>
                  </div>
                </form>
                {% endif %}
              </div>
            </div>
          </div>

          <hr>

        </div> <!-- /container -->
{% endblock %}


{% block java %}
  <script>
        var username = document.querySelector('#id_username');
        var first_name = document.querySelector('#id_first_name');
        var last_name = document.querySelector('#id_last_name');
        var email = document.querySelector('#id_email');
        var phone = document.querySelector('#id_phoneNumber');
        var password1 = document.querySelector('#id_password1');
        var password2 = document.querySelector('#id_password2');
        var phoneNumber = document.querySelector('#id_phoneNumber');
        var label = document.createElement('label');

        username.setAttribute('placeholder',"Username");
        username.setAttribute('class', 'input100');
        first_name.setAttribute('placeholder',"Firstname");
        first_name.setAttribute('class', 'input100');
        last_name.setAttribute('placeholder',"Lastname");
        last_name.setAttribute('class', 'input100');
        email.setAttribute('placeholder',"Email");
        email.setAttribute('class', 'input100');
        phone.setAttribute('placeholder',"Phone Number");
        phone.setAttribute('class', 'input100');
        password1.setAttribute('placeholder',"Password");
        password1.setAttribute('class', 'input100');
        password2.setAttribute('placeholder',"Confirm Password");
        password2.setAttribute('class', 'input100');
        phoneNumber.setAttribute('type', 'number');

        username.required = true;
        first_name.required = true;
        last_name.required = true;
        email.required = true;
        phone.required = true;
        password1.required = true;
        password2.required = true;
        phoneNumber = true;

        var error = document.querySelector('#err');
        error.style.color = red;

    </script>
    {% endblock %}

yctmarket/ent/templates/ent/thanks.html
{% extends 'ent/base.html' %}

{% block title %}Thanks! | {{ block.super }}{% endblock %}


{% block style %}
  <style>
  #fix {
    position: fixed;
    bottom: 0px;
    width: 100%;
  }
  </style>


{% endblock %}



{% block jumbotron %}
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->

          <h1 id='grw' class="display-3">Thank you!</h1>

          <div class="article">
                                       <p>You will be connected to the seller shortly.</p>
                                       <p>An email will be sent to you for notification and a call will be placed to your phone number by the seller.</p>
                                       <p><a class="btn btn-primary btn-lg" href="{% url 'ent:article_list' %}" role="button">Back to Home &raquo;</a></p>
                            </div>

     </main>
{% endblock %}